# Generated by Django 5.1.4 on 2025-01-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(default='shipping_city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='shipping_city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(default='shipping_email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(default='shipping_fullname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
